### ISSUE TITLE
Kendo Ui for Jquery是否可商业使用

### ISSUE THREAD

**Issue by LambertW** [IKKI2000/KendoUI-Admin-Site#3]
同以上标题，想了解一下，项目虽然为MIT性质，但是Kendo UI for Jquery，应该是不允许直接商业化使用的吧？

**Comment by IKKI2000** [comment]
是的~ Kendo UI 只有核心组件和主题库是 Apache 2.0 开源的~ Github地址为：
[https://github.com/telerik/kendo-ui-core](https://github.com/telerik/kendo-ui-core)
专业版只有30天的试用期~ 具体区别见上面链接的 ReadMe 部分~

**Comment by LambertW** [comment]
所以 现在 引用的  kendoui.all.js，是需要购买许可之后才能正式 商业使用吗？

**Comment by IKKI2000** [comment]
是的~
